### ISSUE TITLE
DI GetService doesn't return the instance of HttpClient

### ISSUE THREAD

**Issue by abdulateef** [Turnerj/forem-dotnet#45]
while trying to test the Api using DI from a  .Net Core project i observed that the  GetService does not return HttpClient which throw an exception shown below.

<img width="1440" alt="Screen Shot 2020-08-23 at 6 14 54 PM" src="https://user-images.githubusercontent.com/12833386/90984410-9d821c80-e56c-11ea-8b7f-3e72505d040d.png">

**Comment by Hilyas68** [comment]
I got this error too when implementing with DI. Failed to return an instance of `HttpClient`

**Comment by Turnerj** [comment]
You're right, the `GetService<HttpClient>()` calls in `ApiServiceCollectionExtensions.cs` should actually be `GetRequiredService<HttpClient>()` - this then comes back with a better exception to say that `HttpClient` isn't registered rather than throwing a `NullReferenceException`. The idea is that someone configures the `HttpClient` themselves and adds it to the services collection - this then allows the person to configure proxies, user agents or other fields for the client.

In a project, you would have something like this in the `Startup.cs` file (or wherever the user is configuring all of the other DI things):

```csharp
services.AddHttpClient();
services.AddTransient(provider =>
{
	//This is a workaround till .NET 5 which fixes the issue of no default HttpClient
	return provider.GetRequiredService<IHttpClientFactory>().CreateClient(string.Empty);
});
```

The reason to do this more complicated process of passing in a `HttpClient` and creating it from an `IHttpClientFactory` is due to the "disposable" pattern that `HttpClient` implements. When you dispose a `HttpClient`, it can leave sockets open on the connection which can starve the host system when you dispose of them. I haven't really found precedence in other libraries about how to handle `HttpClient` instances being required. My other libraries I've built do a similar process.

**Comment by Turnerj** [comment]
With this in mind @abdulateef, I'd happily take a PR to change `GetService` to `GetRequiredService` in the `ApiServiceCollectionExtensions.cs` file so the error messages are better.

**Comment by abdulateef** [comment]
Good morning
I will push that today 
thanks
